// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AnlamalkurumlarTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void anlamalkurumlar() {
    // Test name: Anlaşmalı kurumlar
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1766x1013 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1766, 1013);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Anlaşmalı Kurumlar | 
    driver.FindElement(By.LinkText("Anlaşmalı Kurumlar")).Click();
    // 5 | click | css=.odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .lever")).Click();
    // 6 | click | css=.even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(2) .lever")).Click();
    // 7 | click | css=.even:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(4) .lever")).Click();
    // 8 | click | css=.odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .lever")).Click();
    // 9 | click | css=.odd:nth-child(5) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(5) .lever")).Click();
    // 10 | click | css=.odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .fa")).Click();
    // 11 | click | linkText=Geçerli Olduğu Hastane Listesi | 
    driver.FindElement(By.LinkText("Geçerli Olduğu Hastane Listesi")).Click();
    // 12 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 13 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 14 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 15 | type | css=.sorting_asc > .column_search | 8880
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("8880");
    // 16 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 17 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 18 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
  }
}
