// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BannerTanmlama3tipTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void bannerTanmlama3tip() {
    // Test name: Banner Tanımlama (3 tip)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x840 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 840);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Banner İşlemleri | 
    driver.FindElement(By.LinkText("Banner İşlemleri")).Click();
    // 5 | click | linkText=Banner Liste | 
    driver.FindElement(By.LinkText("Banner Liste")).Click();
    // 6 | click | linkText=Ekle | 
    driver.FindElement(By.LinkText("Ekle")).Click();
    // 7 | click | id=BannerHeaderName | 
    driver.FindElement(By.Id("BannerHeaderName")).Click();
    // 8 | type | id=BannerHeaderName | Selenium test genel
    driver.FindElement(By.Id("BannerHeaderName")).SendKeys("Selenium test genel");
    // 9 | click | id=DocumentBase64 | 
    driver.FindElement(By.Id("DocumentBase64")).Click();
    // 10 | type | id=DocumentBase64 | C:\Users\4A Labs\Desktop\Memorial\hakkında jpg.jfif
    driver.FindElement(By.Id("DocumentBase64")).SendKeys("C:\\Users\\4A Labs\\Desktop\\Memorial\\hakkında jpg.jfif");
    // 11 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 12 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 13 | click | id=RedirectTypeId | 
    driver.FindElement(By.Id("RedirectTypeId")).Click();
    // 14 | select | id=RedirectTypeId | label=Uygulama Içi Yönlendirme
    {
      var dropdown = driver.FindElement(By.Id("RedirectTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Uygulama Içi Yönlendirme']")).Click();
    }
    // 15 | click | id=MobilePageId | 
    driver.FindElement(By.Id("MobilePageId")).Click();
    // 16 | select | id=MobilePageId | label=Sayfa 2
    {
      var dropdown = driver.FindElement(By.Id("MobilePageId"));
      dropdown.FindElement(By.XPath("//option[. = 'Sayfa 2']")).Click();
    }
    // 17 | click | id=IsActive | 
    driver.FindElement(By.Id("IsActive")).Click();
    // 18 | select | id=IsActive | label=Pasif
    {
      var dropdown = driver.FindElement(By.Id("IsActive"));
      dropdown.FindElement(By.XPath("//option[. = 'Pasif']")).Click();
    }
    // 19 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 20 | select | id=BannerPublishTypeId | label=Yayın Sonlandı
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayın Sonlandı']")).Click();
    }
    // 21 | click | id=BannerTargetTypeId | 
    driver.FindElement(By.Id("BannerTargetTypeId")).Click();
    // 22 | select | id=BannerTargetTypeId | label=Genel
    {
      var dropdown = driver.FindElement(By.Id("BannerTargetTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Genel']")).Click();
    }
    // 23 | click | id=BannerContent | 
    driver.FindElement(By.Id("BannerContent")).Click();
    // 24 | runScript | window.scrollTo(0,869) | 
    js.ExecuteScript("window.scrollTo(0,869)");
    // 25 | type | id=BannerContent | test
    driver.FindElement(By.Id("BannerContent")).SendKeys("test");
    // 26 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 27 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 28 | click | linkText=Ekle | 
    driver.FindElement(By.LinkText("Ekle")).Click();
    // 29 | click | id=InterfaceTypeId | 
    driver.FindElement(By.Id("InterfaceTypeId")).Click();
    // 30 | select | id=InterfaceTypeId | label=Kurumsal
    {
      var dropdown = driver.FindElement(By.Id("InterfaceTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Kurumsal']")).Click();
    }
    // 31 | click | id=BannerHeaderName | 
    driver.FindElement(By.Id("BannerHeaderName")).Click();
    // 32 | type | id=BannerHeaderName | selenium test favori
    driver.FindElement(By.Id("BannerHeaderName")).SendKeys("selenium test favori");
    // 33 | click | id=DocumentBase64 | 
    driver.FindElement(By.Id("DocumentBase64")).Click();
    // 34 | type | id=DocumentBase64 | C:\Users\4A Labs\Desktop\Memorial\hakkında jpg.jfif
    driver.FindElement(By.Id("DocumentBase64")).SendKeys("C:\\Users\\4A Labs\\Desktop\\Memorial\\hakkında jpg.jfif");
    // 35 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 36 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 37 | click | id=RedirectTypeId | 
    driver.FindElement(By.Id("RedirectTypeId")).Click();
    // 38 | select | id=RedirectTypeId | label=Uygulama Içi Yönlendirme
    {
      var dropdown = driver.FindElement(By.Id("RedirectTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Uygulama Içi Yönlendirme']")).Click();
    }
    // 39 | click | id=MobilePageId | 
    driver.FindElement(By.Id("MobilePageId")).Click();
    // 40 | select | id=MobilePageId | label=Sayfa 3
    {
      var dropdown = driver.FindElement(By.Id("MobilePageId"));
      dropdown.FindElement(By.XPath("//option[. = 'Sayfa 3']")).Click();
    }
    // 41 | click | id=IsActive | 
    driver.FindElement(By.Id("IsActive")).Click();
    // 42 | select | id=IsActive | label=Pasif
    {
      var dropdown = driver.FindElement(By.Id("IsActive"));
      dropdown.FindElement(By.XPath("//option[. = 'Pasif']")).Click();
    }
    // 43 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 44 | select | id=BannerPublishTypeId | label=Yayın Sonlandı
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayın Sonlandı']")).Click();
    }
    // 45 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 46 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 47 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 48 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 49 | click | linkText=Ekle | 
    driver.FindElement(By.LinkText("Ekle")).Click();
    // 50 | click | id=BannerHeaderName | 
    driver.FindElement(By.Id("BannerHeaderName")).Click();
    // 51 | type | id=BannerHeaderName | selenium test kişisel
    driver.FindElement(By.Id("BannerHeaderName")).SendKeys("selenium test kişisel");
    // 52 | click | css=form:nth-child(3) | 
    driver.FindElement(By.CssSelector("form:nth-child(3)")).Click();
    // 53 | click | id=DocumentBase64 | 
    driver.FindElement(By.Id("DocumentBase64")).Click();
    // 54 | type | id=DocumentBase64 | C:\Users\4A Labs\Desktop\Memorial\hakkında jpg.jfif
    driver.FindElement(By.Id("DocumentBase64")).SendKeys("C:\\Users\\4A Labs\\Desktop\\Memorial\\hakkında jpg.jfif");
    // 55 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 56 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 57 | click | id=TargetDescription | 
    driver.FindElement(By.Id("TargetDescription")).Click();
    // 58 | type | id=TargetDescription | test link
    driver.FindElement(By.Id("TargetDescription")).SendKeys("test link");
    // 59 | click | id=BannerTargetTypeId | 
    driver.FindElement(By.Id("BannerTargetTypeId")).Click();
    // 60 | select | id=BannerTargetTypeId | label=Kişiselleştirilmiş
    {
      var dropdown = driver.FindElement(By.Id("BannerTargetTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Kişiselleştirilmiş']")).Click();
    }
    // 61 | click | id=StartAge | 
    driver.FindElement(By.Id("StartAge")).Click();
    // 62 | type | id=StartAge | 5
    driver.FindElement(By.Id("StartAge")).SendKeys("5");
    // 63 | click | id=EndAge | 
    driver.FindElement(By.Id("EndAge")).Click();
    // 64 | type | id=EndAge | 55
    driver.FindElement(By.Id("EndAge")).SendKeys("55");
    // 65 | click | css=#divHedefTip > .row:nth-child(8) | 
    driver.FindElement(By.CssSelector("#divHedefTip > .row:nth-child(8)")).Click();
    // 66 | click | id=GenderId | 
    driver.FindElement(By.Id("GenderId")).Click();
    // 67 | select | id=GenderId | label=Kadin
    {
      var dropdown = driver.FindElement(By.Id("GenderId"));
      dropdown.FindElement(By.XPath("//option[. = 'Kadin']")).Click();
    }
    // 68 | click | id=CityId | 
    driver.FindElement(By.Id("CityId")).Click();
    // 69 | select | id=CityId | label=ANKARA
    {
      var dropdown = driver.FindElement(By.Id("CityId"));
      dropdown.FindElement(By.XPath("//option[. = 'ANKARA']")).Click();
    }
    // 70 | click | id=DistrictId | 
    driver.FindElement(By.Id("DistrictId")).Click();
    // 71 | select | id=DistrictId | label=KEÇIÖREN
    {
      var dropdown = driver.FindElement(By.Id("DistrictId"));
      dropdown.FindElement(By.XPath("//option[. = 'KEÇIÖREN']")).Click();
    }
    // 72 | click | css=.row:nth-child(10) .filter-option | 
    driver.FindElement(By.CssSelector(".row:nth-child(10) .filter-option")).Click();
    // 73 | click | css=li:nth-child(2) .text | 
    driver.FindElement(By.CssSelector("li:nth-child(2) .text")).Click();
    // 74 | removeSelection | id=HospitalId | label=Lütfen Seçiniz
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Lütfen Seçiniz']")).Click();
    }
    // 75 | addSelection | id=HospitalId | label=Memorial Ankara Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Ankara Hastanesi']")).Click();
    }
    // 76 | removeSelection | id=HospitalId | label=Memorial Şişli Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Şişli Hastanesi']")).Click();
    }
    // 77 | click | css=.show li:nth-child(3) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(3) .text")).Click();
    // 78 | addSelection | id=HospitalId | label=Memorial Antalya Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Antalya Hastanesi']")).Click();
    }
    // 79 | click | css=.show li:nth-child(4) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(4) .text")).Click();
    // 80 | addSelection | id=HospitalId | label=Memorial Ataşehir Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Ataşehir Hastanesi']")).Click();
    }
    // 81 | click | css=.show li:nth-child(5) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(5) .text")).Click();
    // 82 | addSelection | id=HospitalId | label=Memorial Bahçelievler Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Bahçelievler Hastanesi']")).Click();
    }
    // 83 | click | linkText=Memorial Dicle Hastanesi | 
    driver.FindElement(By.LinkText("Memorial Dicle Hastanesi")).Click();
    // 84 | addSelection | id=HospitalId | label=Memorial Dicle Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Dicle Hastanesi']")).Click();
    }
    // 85 | click | css=.show li:nth-child(7) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(7) .text")).Click();
    // 86 | addSelection | id=HospitalId | label=Memorial Diyarbakır Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Diyarbakır Hastanesi']")).Click();
    }
    // 87 | click | css=.show li:nth-child(8) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(8) .text")).Click();
    // 88 | addSelection | id=HospitalId | label=Memorial Hizmet Hastanesi
    {
      var dropdown = driver.FindElement(By.Id("HospitalId"));
      dropdown.FindElement(By.XPath("//option[. = 'Memorial Hizmet Hastanesi']")).Click();
    }
    // 89 | click | css=.container-fluid | 
    driver.FindElement(By.CssSelector(".container-fluid")).Click();
    // 90 | click | css=.row:nth-child(12) .filter-option | 
    driver.FindElement(By.CssSelector(".row:nth-child(12) .filter-option")).Click();
    // 91 | click | css=.show li:nth-child(1) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(1) .text")).Click();
    // 92 | addSelection | id=DepartmentId | label=Yenidoğan Yoğun Bakım Ünitesi (Neonatoloji)
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yenidoğan Yoğun Bakım Ünitesi (Neonatoloji)']")).Click();
    }
    // 93 | removeSelection | id=DepartmentId | label=Gastrointestinal Onkolojik Cerrahi Merkezi
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Gastrointestinal Onkolojik Cerrahi Merkezi']")).Click();
    }
    // 94 | click | css=.show li:nth-child(2) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(2) .text")).Click();
    // 95 | addSelection | id=DepartmentId | label=Göğüs Cerrahisi
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Göğüs Cerrahisi']")).Click();
    }
    // 96 | click | css=.show li:nth-child(3) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(3) .text")).Click();
    // 97 | addSelection | id=DepartmentId | label=Girişimsel Radyoloji
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Girişimsel Radyoloji']")).Click();
    }
    // 98 | click | linkText=Genel Cerrahi | 
    driver.FindElement(By.LinkText("Genel Cerrahi")).Click();
    // 99 | addSelection | id=DepartmentId | label=Genel Cerrahi
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Genel Cerrahi']")).Click();
    }
    // 100 | click | linkText=Gastroenteroloji | 
    driver.FindElement(By.LinkText("Gastroenteroloji")).Click();
    // 101 | addSelection | id=DepartmentId | label=Gastroenteroloji
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Gastroenteroloji']")).Click();
    }
    // 102 | click | css=.show li:nth-child(6) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(6) .text")).Click();
    // 103 | addSelection | id=DepartmentId | label=Fizik Tedavi ve Rehabilitasyon
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Fizik Tedavi ve Rehabilitasyon']")).Click();
    }
    // 104 | click | css=.show li:nth-child(7) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(7) .text")).Click();
    // 105 | addSelection | id=DepartmentId | label=Estetik, Plastik ve Rekonstrüktif Cerrahi
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Estetik, Plastik ve Rekonstrüktif Cerrahi']")).Click();
    }
    // 106 | click | css=.container-fluid | 
    driver.FindElement(By.CssSelector(".container-fluid")).Click();
    // 107 | click | css=.row:nth-child(14) .filter-option | 
    driver.FindElement(By.CssSelector(".row:nth-child(14) .filter-option")).Click();
    // 108 | click | css=.show li:nth-child(1) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(1) .text")).Click();
    // 109 | addSelection | id=IllnessId | label=Akciğer kanseri belirtileri, yaşam süresi ve tedavisi
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Akciğer kanseri belirtileri, yaşam süresi ve tedavisi']")).Click();
    }
    // 110 | click | css=.show li:nth-child(2) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(2) .text")).Click();
    // 111 | addSelection | id=IllnessId | label=Apandisit nedir? Belirtileri nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Apandisit nedir? Belirtileri nelerdir?']")).Click();
    }
    // 112 | click | css=.show li:nth-child(3) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(3) .text")).Click();
    // 113 | addSelection | id=IllnessId | label=Aşırı terleme nedenleri ve tedavileri
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Aşırı terleme nedenleri ve tedavileri']")).Click();
    }
    // 114 | click | css=.show li:nth-child(4) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(4) .text")).Click();
    // 115 | addSelection | id=IllnessId | label=Boyun düzleşmesi nedir? Belirtileri ve tedavi yöntemleri nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Boyun düzleşmesi nedir? Belirtileri ve tedavi yöntemleri nelerdir?']")).Click();
    }
    // 116 | click | css=.show li:nth-child(5) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(5) .text")).Click();
    // 117 | addSelection | id=IllnessId | label=Boyun fıtığı belirtileri ve tedavi yöntemleri nedir?
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Boyun fıtığı belirtileri ve tedavi yöntemleri nedir?']")).Click();
    }
    // 118 | click | css=.show li:nth-child(6) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(6) .text")).Click();
    // 119 | addSelection | id=IllnessId | label=Cilt (Deri) Kanseri Belirtileri, Tedavisi Ve Korunma Yöntemleri
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Cilt (Deri) Kanseri Belirtileri, Tedavisi Ve Korunma Yöntemleri']")).Click();
    }
    // 120 | click | css=.show li:nth-child(7) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(7) .text")).Click();
    // 121 | addSelection | id=IllnessId | label=Çölyak hastalığı nedir? Belirti ve tedavi yöntemleri nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Çölyak hastalığı nedir? Belirti ve tedavi yöntemleri nelerdir?']")).Click();
    }
    // 122 | click | css=.show li:nth-child(8) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(8) .text")).Click();
    // 123 | addSelection | id=IllnessId | label=Crohn hastalığı belirtileri ve tedavi yöntemleri neler?
    {
      var dropdown = driver.FindElement(By.Id("IllnessId"));
      dropdown.FindElement(By.XPath("//option[. = 'Crohn hastalığı belirtileri ve tedavi yöntemleri neler?']")).Click();
    }
    // 124 | click | css=.scroll-sidebar | 
    driver.FindElement(By.CssSelector(".scroll-sidebar")).Click();
    // 125 | click | css=.bs-placeholder > .filter-option | 
    driver.FindElement(By.CssSelector(".bs-placeholder > .filter-option")).Click();
    // 126 | click | css=.show li:nth-child(2) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(2) .text")).Click();
    // 127 | removeSelection | id=TreatmentId | label=Botoks nedir? Nasıl yapılır?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Botoks nedir? Nasıl yapılır?']")).Click();
    }
    // 128 | addSelection | id=TreatmentId | label=İmmünoterapi nedir?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'İmmünoterapi nedir?']")).Click();
    }
    // 129 | click | css=.show li:nth-child(3) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(3) .text")).Click();
    // 130 | addSelection | id=TreatmentId | label=İmmünoterapi nedir?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'İmmünoterapi nedir?']")).Click();
    }
    // 131 | click | css=.show li:nth-child(4) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(4) .text")).Click();
    // 132 | addSelection | id=TreatmentId | label=Kemoterapi nedir? Nasıl Uygulanır? Yan Etkileri Nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Kemoterapi nedir? Nasıl Uygulanır? Yan Etkileri Nelerdir?']")).Click();
    }
    // 133 | click | css=.show li:nth-child(5) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(5) .text")).Click();
    // 134 | addSelection | id=TreatmentId | label=Kemoterapi nedir? Nasıl Uygulanır? Yan Etkileri Nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Kemoterapi nedir? Nasıl Uygulanır? Yan Etkileri Nelerdir?']")).Click();
    }
    // 135 | click | css=.show li:nth-child(6) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(6) .text")).Click();
    // 136 | addSelection | id=TreatmentId | label=Radyoterapi nedir? Nasıl Uygulanır? Yan etkileri nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Radyoterapi nedir? Nasıl Uygulanır? Yan etkileri nelerdir?']")).Click();
    }
    // 137 | click | css=.show li:nth-child(7) .text | 
    driver.FindElement(By.CssSelector(".show li:nth-child(7) .text")).Click();
    // 138 | addSelection | id=TreatmentId | label=Radyoterapi nedir? Nasıl Uygulanır? Yan etkileri nelerdir?
    {
      var dropdown = driver.FindElement(By.Id("TreatmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Radyoterapi nedir? Nasıl Uygulanır? Yan etkileri nelerdir?']")).Click();
    }
    // 139 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 140 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 141 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 142 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 143 | click | css=.container-fluid:nth-child(1) | 
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(1)")).Click();
    // 144 | click | css=.scroll-sidebar | 
    driver.FindElement(By.CssSelector(".scroll-sidebar")).Click();
  }
}
