// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BannerGrntlemeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void bannerGrntleme() {
    // Test name: Banner Görüntüleme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x840 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 840);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Banner İşlemleri | 
    driver.FindElement(By.LinkText("Banner İşlemleri")).Click();
    // 5 | click | linkText=Banner Liste | 
    driver.FindElement(By.LinkText("Banner Liste")).Click();
    // 6 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 7 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 8 | click | css=.odd:nth-child(1) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-info > .fa")).Click();
    // 9 | click | id=BannerHeaderName | 
    driver.FindElement(By.Id("BannerHeaderName")).Click();
    // 10 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 11 | type | id=BannerHeaderName | Selenium test genel1
    driver.FindElement(By.Id("BannerHeaderName")).SendKeys("Selenium test genel1");
    // 12 | click | id=IsRedirected | 
    driver.FindElement(By.Id("IsRedirected")).Click();
    // 13 | click | id=IsActive | 
    driver.FindElement(By.Id("IsActive")).Click();
    // 14 | select | id=IsActive | label=Aktif
    {
      var dropdown = driver.FindElement(By.Id("IsActive"));
      dropdown.FindElement(By.XPath("//option[. = 'Aktif']")).Click();
    }
    // 15 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 16 | select | id=BannerPublishTypeId | label=Yayında
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayında']")).Click();
    }
    // 17 | click | id=BannerContent | 
    driver.FindElement(By.Id("BannerContent")).Click();
    // 18 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 19 | type | id=BannerContent | test1
    driver.FindElement(By.Id("BannerContent")).SendKeys("test1");
    // 20 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 21 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 22 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 23 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 24 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 25 | click | css=.odd:nth-child(1) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-info > .fa")).Click();
    // 26 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 27 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 28 | select | id=BannerPublishTypeId | label=Yayın Sonlandı
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayın Sonlandı']")).Click();
    }
    // 29 | click | id=BannerContent | 
    driver.FindElement(By.Id("BannerContent")).Click();
    // 30 | click | id=BannerContent | 
    driver.FindElement(By.Id("BannerContent")).Click();
    // 31 | doubleClick | id=BannerContent | 
    {
      var element = driver.FindElement(By.Id("BannerContent"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    // 32 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 33 | type | id=BannerContent | tamam
    driver.FindElement(By.Id("BannerContent")).SendKeys("tamam");
    // 34 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 35 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 36 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 37 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 38 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 39 | click | css=.even .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".even .btn-info > .fa")).Click();
    // 40 | click | id=BannerHeaderName | 
    driver.FindElement(By.Id("BannerHeaderName")).Click();
    // 41 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 42 | type | id=BannerHeaderName | selenium test favori2
    driver.FindElement(By.Id("BannerHeaderName")).SendKeys("selenium test favori2");
    // 43 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 44 | select | id=BannerPublishTypeId | label=Yayınlanacak
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayınlanacak']")).Click();
    }
    // 45 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 46 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 47 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 48 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 49 | click | css=.even .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".even .btn-info > .fa")).Click();
    // 50 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 51 | select | id=BannerPublishTypeId | label=Yayın Sonlandı
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayın Sonlandı']")).Click();
    }
    // 52 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 53 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 54 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 55 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 56 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 57 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 58 | click | css=.odd:nth-child(3) .btn-info | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .btn-info")).Click();
    // 59 | click | id=BannerHeaderName | 
    driver.FindElement(By.Id("BannerHeaderName")).Click();
    // 60 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 61 | type | id=BannerHeaderName | selenium test kişisel3
    driver.FindElement(By.Id("BannerHeaderName")).SendKeys("selenium test kişisel3");
    // 62 | click | id=IsRedirected | 
    driver.FindElement(By.Id("IsRedirected")).Click();
    // 63 | click | id=IsActive | 
    driver.FindElement(By.Id("IsActive")).Click();
    // 64 | select | id=IsActive | label=Pasif
    {
      var dropdown = driver.FindElement(By.Id("IsActive"));
      dropdown.FindElement(By.XPath("//option[. = 'Pasif']")).Click();
    }
    // 65 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 66 | select | id=BannerPublishTypeId | label=Yayın Sonlandı
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayın Sonlandı']")).Click();
    }
    // 67 | click | id=StartAge | 
    driver.FindElement(By.Id("StartAge")).Click();
    // 68 | type | id=StartAge | 56
    driver.FindElement(By.Id("StartAge")).SendKeys("56");
    // 69 | click | id=EndAge | 
    driver.FindElement(By.Id("EndAge")).Click();
    // 70 | type | id=EndAge | 556
    driver.FindElement(By.Id("EndAge")).SendKeys("556");
    // 71 | click | id=GenderId | 
    driver.FindElement(By.Id("GenderId")).Click();
    // 72 | select | id=GenderId | label=Erkek
    {
      var dropdown = driver.FindElement(By.Id("GenderId"));
      dropdown.FindElement(By.XPath("//option[. = 'Erkek']")).Click();
    }
    // 73 | click | id=DistrictId | 
    driver.FindElement(By.Id("DistrictId")).Click();
    // 74 | select | id=DistrictId | label=KAHRAMANKAZAN
    {
      var dropdown = driver.FindElement(By.Id("DistrictId"));
      dropdown.FindElement(By.XPath("//option[. = 'KAHRAMANKAZAN']")).Click();
    }
    // 75 | click | id=myBtn | 
    driver.FindElement(By.Id("myBtn")).Click();
    // 76 | removeSelection | id=bootstrap-duallistbox-nonselected-list_duallistbox_demo1[] | label=test321
    {
      var dropdown = driver.FindElement(By.Id("bootstrap-duallistbox-nonselected-list_duallistbox_demo1[]"));
      dropdown.FindElement(By.XPath("//option[. = 'test321']")).Click();
    }
    // 77 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 78 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 79 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 80 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 81 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 82 | click | css=.odd:nth-child(3) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .btn-info > .fa")).Click();
    // 83 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 84 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 85 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 86 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 87 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 88 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
  }
}
