// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BannerSilmeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void bannerSilme() {
    // Test name: Banner Silme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x840 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 840);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Banner İşlemleri | 
    driver.FindElement(By.LinkText("Banner İşlemleri")).Click();
    // 5 | click | linkText=Banner Liste | 
    driver.FindElement(By.LinkText("Banner Liste")).Click();
    // 6 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 7 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 8 | click | css=.odd:nth-child(1) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-info > .fa")).Click();
    // 9 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 10 | select | id=BannerPublishTypeId | label=Yayında
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayında']")).Click();
    }
    // 11 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 12 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 13 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 14 | type | css=th:nth-child(2) > .column_search | sele
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("sele");
    // 15 | click | css=.odd:nth-child(1) .btn-danger > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-danger > .fa")).Click();
    // 16 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 17 | mouseOver | css=.swal-button | 
    {
      var element = driver.FindElement(By.CssSelector(".swal-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 18 | mouseOut | css=.swal-button | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 19 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 20 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 21 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 22 | click | id=dtBanner_wrapper | 
    driver.FindElement(By.Id("dtBanner_wrapper")).Click();
    // 23 | click | css=.odd:nth-child(1) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-info > .fa")).Click();
    // 24 | click | id=BannerPublishTypeId | 
    driver.FindElement(By.Id("BannerPublishTypeId")).Click();
    // 25 | select | id=BannerPublishTypeId | label=Yayınlanacak
    {
      var dropdown = driver.FindElement(By.Id("BannerPublishTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Yayınlanacak']")).Click();
    }
    // 26 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 27 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 28 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 29 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 30 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 31 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 32 | click | id=dtBanner_wrapper | 
    driver.FindElement(By.Id("dtBanner_wrapper")).Click();
    // 33 | click | css=.odd:nth-child(1) .btn-danger > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-danger > .fa")).Click();
    // 34 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 35 | mouseOver | css=.swal-button | 
    {
      var element = driver.FindElement(By.CssSelector(".swal-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 36 | mouseOut | css=.swal-button | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 37 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 38 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 39 | type | css=th:nth-child(2) > .column_search | sele
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("sele");
    // 40 | click | css=.dt-buttons | 
    driver.FindElement(By.CssSelector(".dt-buttons")).Click();
    // 41 | click | css=.odd .btn-danger > .fa | 
    driver.FindElement(By.CssSelector(".odd .btn-danger > .fa")).Click();
    // 42 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 43 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 44 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 45 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 46 | click | id=dtBanner_wrapper | 
    driver.FindElement(By.Id("dtBanner_wrapper")).Click();
    // 47 | click | css=.fa-trash-o | 
    driver.FindElement(By.CssSelector(".fa-trash-o")).Click();
    // 48 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 49 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 50 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 51 | type | css=th:nth-child(2) > .column_search | sele
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("sele");
    // 52 | click | css=.dt-buttons | 
    driver.FindElement(By.CssSelector(".dt-buttons")).Click();
  }
}
