// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DoktorlemleriTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void doktorlemleri() {
    // Test name: Doktor İşlemleri
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x840 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 840);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Doktor İşlemleri | 
    driver.FindElement(By.LinkText("Doktor İşlemleri")).Click();
    // 5 | click | css=.odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .lever")).Click();
    // 6 | click | css=.even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(2) .lever")).Click();
    // 7 | click | css=.odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .lever")).Click();
    // 8 | click | css=.even:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(4) .lever")).Click();
    // 9 | click | css=.odd:nth-child(5) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(5) .lever")).Click();
    // 10 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 11 | type | css=.sorting_asc > .column_search | 24
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("24");
    // 12 | click | css=.odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .fa")).Click();
    // 13 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 14 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 15 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 16 | click | linkText=Görev Aldığı Tıbbi Birimler | 
    driver.FindElement(By.LinkText("Görev Aldığı Tıbbi Birimler")).Click();
    // 17 | click | css=#dtMedicalUnit .odd > td:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector("#dtMedicalUnit .odd > td:nth-child(4) .lever")).Click();
    // 18 | click | css=#dtMedicalUnit .odd > td:nth-child(5) .lever | 
    driver.FindElement(By.CssSelector("#dtMedicalUnit .odd > td:nth-child(5) .lever")).Click();
    // 19 | click | linkText=Uzmanlıklar | 
    driver.FindElement(By.LinkText("Uzmanlıklar")).Click();
    // 20 | click | css=#dtSpecialistIllnesses .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistIllnesses .odd:nth-child(1) .lever")).Click();
    // 21 | click | css=#dtSpecialistIllnesses .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistIllnesses .even:nth-child(2) .lever")).Click();
    // 22 | click | css=#dtSpecialistIllnesses .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistIllnesses .odd:nth-child(3) .lever")).Click();
    // 23 | click | linkText=Tedaviler | 
    driver.FindElement(By.LinkText("Tedaviler")).Click();
    // 24 | click | css=#dtSpecialistTreatments .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistTreatments .odd:nth-child(1) .lever")).Click();
    // 25 | click | css=#dtSpecialistTreatments .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistTreatments .even:nth-child(2) .lever")).Click();
    // 26 | click | css=#dtSpecialistTreatments .odd:nth-child(3) label | 
    driver.FindElement(By.CssSelector("#dtSpecialistTreatments .odd:nth-child(3) label")).Click();
    // 27 | click | css=.nav-item:nth-child(6) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) .hidden-xs-down")).Click();
    // 28 | click | css=.odd:nth-child(1) > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) > td:nth-child(6) .lever")).Click();
    // 29 | click | css=.even > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".even > td:nth-child(6) .lever")).Click();
    // 30 | click | css=.odd:nth-child(3) > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) > td:nth-child(6) .lever")).Click();
    // 31 | click | css=.nav-item:nth-child(7) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(7) .hidden-xs-down")).Click();
    // 32 | click | css=#dtDoctorGraduations .odd:nth-child(1) label | 
    driver.FindElement(By.CssSelector("#dtDoctorGraduations .odd:nth-child(1) label")).Click();
    // 33 | click | css=#dtDoctorGraduations .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorGraduations .even:nth-child(2) .lever")).Click();
    // 34 | click | css=#dtDoctorGraduations .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorGraduations .odd:nth-child(3) .lever")).Click();
    // 35 | click | linkText=Kişisel Bilgiler | 
    driver.FindElement(By.LinkText("Kişisel Bilgiler")).Click();
    // 36 | click | linkText=Yorumlar | 
    driver.FindElement(By.LinkText("Yorumlar")).Click();
    // 37 | click | css=#dtDoctorPatientThanks .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .odd:nth-child(1) .lever")).Click();
    // 38 | click | css=#dtDoctorPatientThanks .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .even:nth-child(2) .lever")).Click();
    // 39 | click | css=#dtDoctorPatientThanks .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .odd:nth-child(3) .lever")).Click();
    // 40 | click | css=#dtDoctorPatientThanks .even:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .even:nth-child(4) .lever")).Click();
    // 41 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 42 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 43 | type | css=.sorting_asc > .column_search | 24
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("24");
    // 44 | click | css=.odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .fa")).Click();
    // 45 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 46 | click | css=.nav-item:nth-child(3) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) .hidden-xs-down")).Click();
    // 47 | click | css=.nav-item:nth-child(3) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) .hidden-xs-down")).Click();
    // 48 | click | css=#dtMedicalUnit .odd > td:nth-child(5) .lever | 
    driver.FindElement(By.CssSelector("#dtMedicalUnit .odd > td:nth-child(5) .lever")).Click();
    // 49 | click | css=#dtMedicalUnit .even > td:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector("#dtMedicalUnit .even > td:nth-child(4) .lever")).Click();
    // 50 | click | linkText=Uzmanlıklar | 
    driver.FindElement(By.LinkText("Uzmanlıklar")).Click();
    // 51 | click | css=#dtSpecialistIllnesses .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistIllnesses .odd:nth-child(1) .lever")).Click();
    // 52 | click | css=#dtSpecialistIllnesses .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistIllnesses .even:nth-child(2) .lever")).Click();
    // 53 | click | css=#dtSpecialistIllnesses .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistIllnesses .odd:nth-child(3) .lever")).Click();
    // 54 | click | linkText=Tedaviler | 
    driver.FindElement(By.LinkText("Tedaviler")).Click();
    // 55 | click | css=#dtSpecialistTreatments .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistTreatments .odd:nth-child(1) .lever")).Click();
    // 56 | click | css=#dtSpecialistTreatments .even:nth-child(2) label | 
    driver.FindElement(By.CssSelector("#dtSpecialistTreatments .even:nth-child(2) label")).Click();
    // 57 | click | css=#dtSpecialistTreatments .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtSpecialistTreatments .odd:nth-child(3) .lever")).Click();
    // 58 | click | css=.nav-item:nth-child(6) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) .hidden-xs-down")).Click();
    // 59 | click | css=.odd:nth-child(1) > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) > td:nth-child(6) .lever")).Click();
    // 60 | click | css=.even > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".even > td:nth-child(6) .lever")).Click();
    // 61 | click | css=.odd:nth-child(3) > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) > td:nth-child(6) .lever")).Click();
    // 62 | click | linkText=Eğitim | 
    driver.FindElement(By.LinkText("Eğitim")).Click();
    // 63 | click | css=#dtDoctorGraduations .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorGraduations .odd:nth-child(1) .lever")).Click();
    // 64 | click | css=#dtDoctorGraduations .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorGraduations .even:nth-child(2) .lever")).Click();
    // 65 | click | css=#dtDoctorGraduations .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorGraduations .odd:nth-child(3) .lever")).Click();
    // 66 | click | css=.nav-item:nth-child(8) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(8) .hidden-xs-down")).Click();
    // 67 | click | css=.nav-item:nth-child(9) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(9) .hidden-xs-down")).Click();
    // 68 | click | css=#dtDoctorPatientThanks .odd:nth-child(1) label | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .odd:nth-child(1) label")).Click();
    // 69 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 70 | click | css=#dtDoctorPatientThanks .even:nth-child(2) label | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .even:nth-child(2) label")).Click();
    // 71 | click | css=#dtDoctorPatientThanks .odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector("#dtDoctorPatientThanks .odd:nth-child(3) .lever")).Click();
    // 72 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 73 | click | css=.odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .lever")).Click();
    // 74 | click | css=.even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(2) .lever")).Click();
    // 75 | click | css=.odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .lever")).Click();
  }
}
