// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EtiketListesiTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void etiketListesi() {
    // Test name: Etiket Listesi
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x840 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 840);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Etiket İşlemleri | 
    driver.FindElement(By.LinkText("Etiket İşlemleri")).Click();
    // 5 | click | linkText=Etiket Listesi | 
    driver.FindElement(By.LinkText("Etiket Listesi")).Click();
    // 6 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 7 | type | css=th:nth-child(2) > .column_search | sele
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("sele");
    // 8 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 9 | click | id=TicketName | 
    driver.FindElement(By.Id("TicketName")).Click();
    // 10 | type | id=TicketName | selenium test1
    driver.FindElement(By.Id("TicketName")).SendKeys("selenium test1");
    // 11 | click | id=Filter | 
    driver.FindElement(By.Id("Filter")).Click();
    // 12 | click | id=Interest | 
    driver.FindElement(By.Id("Interest")).Click();
    // 13 | click | css=.filter-option | 
    driver.FindElement(By.CssSelector(".filter-option")).Click();
    // 14 | click | linkText=Evde Doktor | 
    driver.FindElement(By.LinkText("Evde Doktor")).Click();
    // 15 | removeSelection | id=Categori | label=Evde Doktor
    {
      var dropdown = driver.FindElement(By.Id("Categori"));
      dropdown.FindElement(By.XPath("//option[. = 'Evde Doktor']")).Click();
    }
    // 16 | addSelection | id=Categori | label=Evde Görüntüleme
    {
      var dropdown = driver.FindElement(By.Id("Categori"));
      dropdown.FindElement(By.XPath("//option[. = 'Evde Görüntüleme']")).Click();
    }
    // 17 | addSelection | id=Categori | label=Evde Hemşire
    {
      var dropdown = driver.FindElement(By.Id("Categori"));
      dropdown.FindElement(By.XPath("//option[. = 'Evde Hemşire']")).Click();
    }
    // 18 | click | css=.scroll-sidebar | 
    driver.FindElement(By.CssSelector(".scroll-sidebar")).Click();
    // 19 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 20 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 21 | click | css=th:nth-child(2) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).Click();
    // 22 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
    // 23 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 24 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 25 | type | css=th:nth-child(2) > .column_search | selen
    driver.FindElement(By.CssSelector("th:nth-child(2) > .column_search")).SendKeys("selen");
  }
}
