// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HzlEriimAraGrntlemeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void hzlEriimAraGrntleme() {
    // Test name: Hızlı Erişim Araç Görüntüleme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Hızlı Erişim Araç | 
    driver.FindElement(By.LinkText("Hızlı Erişim Araç")).Click();
    // 5 | click | linkText=Hızlı Erişim Araç Liste | 
    driver.FindElement(By.LinkText("Hızlı Erişim Araç Liste")).Click();
    // 6 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 7 | type | css=.sorting_asc > .column_search | 555
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("555");
    // 8 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 9 | click | id=InterfaceTypeId | 
    driver.FindElement(By.Id("InterfaceTypeId")).Click();
    // 10 | select | id=InterfaceTypeId | label=Evde Saglik
    {
      var dropdown = driver.FindElement(By.Id("InterfaceTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'Evde Saglik']")).Click();
    }
    // 11 | click | id=ButtonName | 
    driver.FindElement(By.Id("ButtonName")).Click();
    // 12 | type | id=ButtonName | selenium test2
    driver.FindElement(By.Id("ButtonName")).SendKeys("selenium test2");
    // 13 | click | id=RedirectTypeId | 
    driver.FindElement(By.Id("RedirectTypeId")).Click();
    // 14 | select | id=RedirectTypeId | label=URL Yönlendirmesi
    {
      var dropdown = driver.FindElement(By.Id("RedirectTypeId"));
      dropdown.FindElement(By.XPath("//option[. = 'URL Yönlendirmesi']")).Click();
    }
    // 15 | click | id=TargetDescription | 
    driver.FindElement(By.Id("TargetDescription")).Click();
    // 16 | type | id=TargetDescription | www.google.com.tr
    driver.FindElement(By.Id("TargetDescription")).SendKeys("www.google.com.tr");
    // 17 | click | id=IsActive | 
    driver.FindElement(By.Id("IsActive")).Click();
    // 18 | select | id=IsActive | label=Pasif
    {
      var dropdown = driver.FindElement(By.Id("IsActive"));
      dropdown.FindElement(By.XPath("//option[. = 'Pasif']")).Click();
    }
    // 19 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 20 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 21 | click | css=.odd:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .lever")).Click();
    // 22 | click | css=.odd:nth-child(3) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .btn-info > .fa")).Click();
    // 23 | click | id=IsActive | 
    driver.FindElement(By.Id("IsActive")).Click();
    // 24 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 25 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 26 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 27 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 28 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 29 | type | css=.sorting_asc > .column_search | 5
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("5");
  }
}
