// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HzlEriimAraSilmeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void hzlEriimAraSilme() {
    // Test name: Hızlı Erişim Araç Silme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Hızlı Erişim Araç | 
    driver.FindElement(By.LinkText("Hızlı Erişim Araç")).Click();
    // 5 | click | linkText=Hızlı Erişim Araç Liste | 
    driver.FindElement(By.LinkText("Hızlı Erişim Araç Liste")).Click();
    // 6 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 7 | type | css=.sorting_asc > .column_search | 555
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("555");
    // 8 | click | css=.lever | 
    driver.FindElement(By.CssSelector(".lever")).Click();
    // 9 | click | css=.container-fluid:nth-child(1) | 
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(1)")).Click();
    // 10 | click | css=.fa-trash-o | 
    driver.FindElement(By.CssSelector(".fa-trash-o")).Click();
    // 11 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 12 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 13 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 14 | type | css=.sorting_asc > .column_search | 55
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("55");
    // 15 | click | css=.container-fluid:nth-child(30) | 
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(30)")).Click();
  }
}
