// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LetiimformlistesiDzenlenecekTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void letiimformlistesiDzenlenecek() {
    // Test name: İletişim form listesi (Düzenlenecek)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=İletişim Formu | 
    driver.FindElement(By.LinkText("İletişim Formu")).Click();
    // 5 | click | linkText=İletişim Form Listesi | 
    driver.FindElement(By.LinkText("İletişim Form Listesi")).Click();
    // 7 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 8 | type | css=.sorting_asc > .column_search | bekl
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("bekl");
    // 9 | click | css=.dt-buttons | 
    driver.FindElement(By.CssSelector(".dt-buttons")).Click();
    // 10 | click | css=.odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) .fa")).Click();
    // 11 | click | css=.close > span | 
    driver.FindElement(By.CssSelector(".close > span")).Click();
    // 12 | click | css=.dt-buttons | 
    driver.FindElement(By.CssSelector(".dt-buttons")).Click();
  }
}
