// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KategoriTanmlamaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void kategoriTanmlama() {
    // Test name: Kategori Tanımlama 
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x840 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 840);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Kategori İşlemleri | 
    driver.FindElement(By.LinkText("Kategori İşlemleri")).Click();
    // 5 | click | linkText=Kategori Liste | 
    driver.FindElement(By.LinkText("Kategori Liste")).Click();
    // 6 | click | linkText=Ekle | 
    driver.FindElement(By.LinkText("Ekle")).Click();
    // 7 | click | id=CategoryName | 
    driver.FindElement(By.Id("CategoryName")).Click();
    // 8 | type | id=CategoryName | selenium test lab pak
    driver.FindElement(By.Id("CategoryName")).SendKeys("selenium test lab pak");
    // 9 | click | id=CategoryImage | 
    driver.FindElement(By.Id("CategoryImage")).Click();
    // 10 | type | id=CategoryImage | C:\Users\4A Labs\Desktop\Memorial\hakkında jpg.jfif
    driver.FindElement(By.Id("CategoryImage")).SendKeys("C:\\Users\\4A Labs\\Desktop\\Memorial\\hakkında jpg.jfif");
    // 11 | click | id=Url | 
    driver.FindElement(By.Id("Url")).Click();
    // 12 | type | id=Url | https://cms.memorial.4alabs.com/
    driver.FindElement(By.Id("Url")).SendKeys("https://cms.memorial.4alabs.com/");
    // 13 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 14 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 15 | click | linkText=Ekle | 
    driver.FindElement(By.LinkText("Ekle")).Click();
    // 16 | click | id=CategoryName | 
    driver.FindElement(By.Id("CategoryName")).Click();
    // 17 | type | id=CategoryName | selenium test test grubu
    driver.FindElement(By.Id("CategoryName")).SendKeys("selenium test test grubu");
    // 18 | click | css=.card-body | 
    driver.FindElement(By.CssSelector(".card-body")).Click();
    // 19 | click | id=ParentId | 
    driver.FindElement(By.Id("ParentId")).Click();
    // 20 | select | id=ParentId | label=Test Grubu
    {
      var dropdown = driver.FindElement(By.Id("ParentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Test Grubu']")).Click();
    }
    // 21 | click | id=Url | 
    driver.FindElement(By.Id("Url")).Click();
    // 22 | type | id=Url | https://cms.memorial.4alabs.com/
    driver.FindElement(By.Id("Url")).SendKeys("https://cms.memorial.4alabs.com/");
    // 23 | click | css=.note-editable | 
    driver.FindElement(By.CssSelector(".note-editable")).Click();
    // 24 | runScript | window.scrollTo(0,400) | 
    js.ExecuteScript("window.scrollTo(0,400)");
    // 25 | editContent | css=.note-editable | <p>test</p>
    {
      var element = driver.FindElement(By.CssSelector(".note-editable"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test</p>'}", element);
    }
    // 26 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 27 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 28 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 29 | type | css=th:nth-child(1) > .form-control | selenium
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("selenium");
  }
}
