// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KategoriGrntlemeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void kategoriGrntleme() {
    // Test name: Kategori Görüntüleme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Kategori İşlemleri | 
    driver.FindElement(By.LinkText("Kategori İşlemleri")).Click();
    // 5 | click | linkText=Kategori Liste | 
    driver.FindElement(By.LinkText("Kategori Liste")).Click();
    // 6 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 7 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 8 | type | css=th:nth-child(1) > .form-control | selen
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("selen");
    // 9 | click | css=.odd:nth-child(3) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .btn-info > .fa")).Click();
    // 10 | click | id=ParentId | 
    driver.FindElement(By.Id("ParentId")).Click();
    // 11 | select | id=ParentId | label=Evde Doktor
    {
      var dropdown = driver.FindElement(By.Id("ParentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Evde Doktor']")).Click();
    }
    // 12 | click | id=CategoryName | 
    driver.FindElement(By.Id("CategoryName")).Click();
    // 13 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 14 | type | id=CategoryName | selenium test evde doktor
    driver.FindElement(By.Id("CategoryName")).SendKeys("selenium test evde doktor");
    // 15 | click | id=CategoryImage | 
    driver.FindElement(By.Id("CategoryImage")).Click();
    // 16 | type | id=CategoryImage | C:\Users\4A Labs\Desktop\Memorial\tarih 1.png
    driver.FindElement(By.Id("CategoryImage")).SendKeys("C:\\Users\\4A Labs\\Desktop\\Memorial\\tarih 1.png");
    // 17 | click | id=Url | 
    driver.FindElement(By.Id("Url")).Click();
    // 18 | mouseOver | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3 > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 19 | type | id=Url | https://cms.memorial.4alabs.com/1
    driver.FindElement(By.Id("Url")).SendKeys("https://cms.memorial.4alabs.com/1");
    // 20 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 21 | mouseOut | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 22 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 23 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 24 | type | css=th:nth-child(1) > .form-control | selen
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("selen");
    // 25 | click | css=.even:nth-child(4) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".even:nth-child(4) .btn-info > .fa")).Click();
    // 26 | click | id=CategoryName | 
    driver.FindElement(By.Id("CategoryName")).Click();
    // 27 | type | id=CategoryName | selenium test test açıklama2
    driver.FindElement(By.Id("CategoryName")).SendKeys("selenium test test açıklama2");
    // 28 | click | id=Url | 
    driver.FindElement(By.Id("Url")).Click();
    // 29 | mouseOver | css=.note-para > .note-btn:nth-child(2) | 
    {
      var element = driver.FindElement(By.CssSelector(".note-para > .note-btn:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 30 | mouseOut | css=.note-para > .note-btn:nth-child(2) | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 31 | type | id=Url | https://cms.memorial.4alabs.com/2
    driver.FindElement(By.Id("Url")).SendKeys("https://cms.memorial.4alabs.com/2");
    // 32 | click | css=.tooltip-inner | 
    driver.FindElement(By.CssSelector(".tooltip-inner")).Click();
    // 33 | click | css=.note-editable > p | 
    driver.FindElement(By.CssSelector(".note-editable > p")).Click();
    // 34 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 35 | mouseOver | css=.note-fontname .note-btn | 
    {
      var element = driver.FindElement(By.CssSelector(".note-fontname .note-btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 36 | mouseOut | css=.note-fontname .note-btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 37 | editContent | css=.note-editable | <p>test2</p>
    {
      var element = driver.FindElement(By.CssSelector(".note-editable"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test2</p>'}", element);
    }
    // 38 | click | id=ParentId | 
    driver.FindElement(By.Id("ParentId")).Click();
    // 39 | click | css=.scroll-sidebar | 
    driver.FindElement(By.CssSelector(".scroll-sidebar")).Click();
    // 40 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 41 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 42 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 43 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 44 | type | css=th:nth-child(1) > .form-control | selen
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("selen");
    // 45 | click | css=.odd:nth-child(3) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .btn-info > .fa")).Click();
    // 46 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 47 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 48 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 49 | type | css=th:nth-child(1) > .form-control | selen
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("selen");
    // 50 | click | css=.odd:nth-child(5) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd:nth-child(5) .btn-info > .fa")).Click();
    // 51 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 52 | click | id=CategoryName | 
    driver.FindElement(By.Id("CategoryName")).Click();
    // 53 | type | id=CategoryName | selenium sil tamamlandı
    driver.FindElement(By.Id("CategoryName")).SendKeys("selenium sil tamamlandı");
    // 54 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 55 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 56 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 57 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 58 | type | css=th:nth-child(1) > .form-control | selen
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("selen");
    // 59 | click | css=.even:nth-child(4) .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".even:nth-child(4) .btn-info > .fa")).Click();
    // 60 | click | id=CategoryName | 
    driver.FindElement(By.Id("CategoryName")).Click();
    // 61 | runScript | window.scrollTo(0,1) | 
    js.ExecuteScript("window.scrollTo(0,1)");
    // 62 | mouseOver | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3 > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 63 | type | id=CategoryName | selenium sil tamam2
    driver.FindElement(By.Id("CategoryName")).SendKeys("selenium sil tamam2");
    // 64 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 65 | mouseOut | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 66 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 67 | click | id=CategoryImage | 
    driver.FindElement(By.Id("CategoryImage")).Click();
    // 68 | type | id=CategoryImage | C:\Users\4A Labs\Desktop\Memorial\tarih 1.png
    driver.FindElement(By.Id("CategoryImage")).SendKeys("C:\\Users\\4A Labs\\Desktop\\Memorial\\tarih 1.png");
    // 69 | mouseOver | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3 > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 70 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 71 | mouseOut | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 72 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 73 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 74 | type | css=th:nth-child(1) > .form-control | tamam
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("tamam");
  }
}
