// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KullancSilmeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void kullancSilme() {
    // Test name: Kullanıcı Silme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Kullanıcı İşlemleri | 
    driver.FindElement(By.LinkText("Kullanıcı İşlemleri")).Click();
    // 5 | click | linkText=Kullanıcı Liste | 
    driver.FindElement(By.LinkText("Kullanıcı Liste")).Click();
    // 6 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 7 | type | css=th:nth-child(1) > .form-control | sel
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("sel");
    // 8 | click | css=th:nth-child(2) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).Click();
    // 9 | type | css=th:nth-child(2) > .form-control | sel@test1.com
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).SendKeys("sel@test1.com");
    // 10 | click | css=.fa-trash-o | 
    driver.FindElement(By.CssSelector(".fa-trash-o")).Click();
    // 11 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
  }
}
