// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KullancTanmlamaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void kullancTanmlama() {
    // Test name: Kullanıcı Tanımlama
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Kullanıcı İşlemleri | 
    driver.FindElement(By.LinkText("Kullanıcı İşlemleri")).Click();
    // 5 | click | linkText=Kullanıcı Liste | 
    driver.FindElement(By.LinkText("Kullanıcı Liste")).Click();
    // 6 | click | linkText=Ekle | 
    driver.FindElement(By.LinkText("Ekle")).Click();
    // 7 | click | id=FirstName | 
    driver.FindElement(By.Id("FirstName")).Click();
    // 8 | type | id=FirstName | sel
    driver.FindElement(By.Id("FirstName")).SendKeys("sel");
    // 9 | type | id=LastName | test
    driver.FindElement(By.Id("LastName")).SendKeys("test");
    // 10 | type | id=Email | sel@test1.com
    driver.FindElement(By.Id("Email")).SendKeys("sel@test1.com");
    // 11 | type | id=Department | test
    driver.FindElement(By.Id("Department")).SendKeys("test");
    // 12 | type | id=Title | test
    driver.FindElement(By.Id("Title")).SendKeys("test");
    // 13 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 14 | type | id=Description | test
    driver.FindElement(By.Id("Description")).SendKeys("test");
    // 15 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 16 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 17 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
  }
}
