// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KullancListelemeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void kullancListeleme() {
    // Test name: Kullanıcı Listeleme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Kullanıcı İşlemleri | 
    driver.FindElement(By.LinkText("Kullanıcı İşlemleri")).Click();
    // 5 | click | linkText=Kullanıcı Liste | 
    driver.FindElement(By.LinkText("Kullanıcı Liste")).Click();
    // 6 | click | css=th:nth-child(1) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).Click();
    // 7 | type | css=th:nth-child(1) > .form-control | sel
    driver.FindElement(By.CssSelector("th:nth-child(1) > .form-control")).SendKeys("sel");
    // 8 | click | css=.even .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".even .btn-info > .fa")).Click();
    // 9 | click | id=FirstName | 
    driver.FindElement(By.Id("FirstName")).Click();
    // 10 | type | id=FirstName | sel1
    driver.FindElement(By.Id("FirstName")).SendKeys("sel1");
    // 11 | click | id=LastName | 
    driver.FindElement(By.Id("LastName")).Click();
    // 12 | type | id=LastName | test1
    driver.FindElement(By.Id("LastName")).SendKeys("test1");
    // 13 | click | id=Email | 
    driver.FindElement(By.Id("Email")).Click();
    // 14 | type | id=Email | sel@test1.com1
    driver.FindElement(By.Id("Email")).SendKeys("sel@test1.com1");
    // 15 | click | id=Department | 
    driver.FindElement(By.Id("Department")).Click();
    // 16 | type | id=Department | test1
    driver.FindElement(By.Id("Department")).SendKeys("test1");
    // 17 | click | id=Title | 
    driver.FindElement(By.Id("Title")).Click();
    // 18 | type | id=Title | test1
    driver.FindElement(By.Id("Title")).SendKeys("test1");
    // 19 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 20 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 21 | click | id=FirstName | 
    driver.FindElement(By.Id("FirstName")).Click();
    // 22 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 23 | click | css=th:nth-child(2) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).Click();
    // 24 | type | css=th:nth-child(2) > .form-control | sel@te
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).SendKeys("sel@te");
    // 25 | click | css=.odd .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd .btn-info > .fa")).Click();
    // 26 | click | id=FirstName | 
    driver.FindElement(By.Id("FirstName")).Click();
    // 27 | type | id=FirstName | sel
    driver.FindElement(By.Id("FirstName")).SendKeys("sel");
    // 28 | click | id=LastName | 
    driver.FindElement(By.Id("LastName")).Click();
    // 29 | type | id=LastName | test
    driver.FindElement(By.Id("LastName")).SendKeys("test");
    // 30 | click | id=Email | 
    driver.FindElement(By.Id("Email")).Click();
    // 31 | type | id=Email | sel@test1.com
    driver.FindElement(By.Id("Email")).SendKeys("sel@test1.com");
    // 32 | click | id=Department | 
    driver.FindElement(By.Id("Department")).Click();
    // 33 | type | id=Department | test
    driver.FindElement(By.Id("Department")).SendKeys("test");
    // 34 | click | id=Title | 
    driver.FindElement(By.Id("Title")).Click();
    // 35 | type | id=Title | test
    driver.FindElement(By.Id("Title")).SendKeys("test");
    // 36 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 37 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 38 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 39 | click | id=roleId | 
    driver.FindElement(By.Id("roleId")).Click();
    // 40 | select | id=roleId | label=ugur
    {
      var dropdown = driver.FindElement(By.Id("roleId"));
      dropdown.FindElement(By.XPath("//option[. = 'ugur']")).Click();
    }
    // 41 | click | id=btnKullaniciRolEkle | 
    driver.FindElement(By.Id("btnKullaniciRolEkle")).Click();
    // 42 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 43 | click | css=.fa-trash-o | 
    driver.FindElement(By.CssSelector(".fa-trash-o")).Click();
    // 44 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 45 | click | id=btnKullaniciRolEkle | 
    driver.FindElement(By.Id("btnKullaniciRolEkle")).Click();
    // 46 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 47 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 48 | click | css=th:nth-child(2) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).Click();
    // 49 | type | css=th:nth-child(2) > .form-control | sel
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).SendKeys("sel");
    // 50 | click | css=.odd .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd .btn-info > .fa")).Click();
    // 51 | click | linkText=Roller | 
    driver.FindElement(By.LinkText("Roller")).Click();
    // 52 | mouseOver | css=.btn-danger:nth-child(1) | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-danger:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 53 | mouseOut | css=.btn-danger:nth-child(1) | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 54 | click | css=.fa-trash-o | 
    driver.FindElement(By.CssSelector(".fa-trash-o")).Click();
    // 55 | mouseOver | css=.fa-trash-o | 
    {
      var element = driver.FindElement(By.CssSelector(".fa-trash-o"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 56 | mouseOut | css=.fa-trash-o | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 57 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 58 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 59 | click | css=th:nth-child(2) > .form-control | 
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).Click();
    // 60 | type | css=th:nth-child(2) > .form-control | sel
    driver.FindElement(By.CssSelector("th:nth-child(2) > .form-control")).SendKeys("sel");
    // 61 | click | css=.odd .btn-info > .fa | 
    driver.FindElement(By.CssSelector(".odd .btn-info > .fa")).Click();
    // 62 | click | css=.card | 
    driver.FindElement(By.CssSelector(".card")).Click();
    // 63 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
  }
}
