// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class MenuTanmlamaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void menuTanmlama() {
    // Test name: Menu Tanımlama
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Menu İşlemleri | 
    driver.FindElement(By.LinkText("Menu İşlemleri")).Click();
    // 5 | click | linkText=Menu Tanımlama | 
    driver.FindElement(By.LinkText("Menu Tanımlama")).Click();
    // 6 | click | id=Name | 
    driver.FindElement(By.Id("Name")).Click();
    // 7 | type | id=Name | Selenium Create
    driver.FindElement(By.Id("Name")).SendKeys("Selenium Create");
    // 8 | type | id=Controller | test
    driver.FindElement(By.Id("Controller")).SendKeys("test");
    // 9 | type | id=Action | test
    driver.FindElement(By.Id("Action")).SendKeys("test");
    // 10 | select | id=ParentId | label=Tanımlamalar
    {
      var dropdown = driver.FindElement(By.Id("ParentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Tanımlamalar']")).Click();
    }
    // 11 | type | id=Href | test
    driver.FindElement(By.Id("Href")).SendKeys("test");
    // 12 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 13 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 14 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 15 | type | css=.sorting_asc > .column_search | selen
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("selen");
  }
}
