// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class MenuGrntleTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void menuGrntle() {
    // Test name: Menu Görüntüle
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Menu İşlemleri | 
    driver.FindElement(By.LinkText("Menu İşlemleri")).Click();
    // 5 | click | linkText=Menu Listesi | 
    driver.FindElement(By.LinkText("Menu Listesi")).Click();
    // 6 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 7 | type | css=.sorting_asc > .column_search | selen
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("selen");
    // 8 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 9 | click | id=Name | 
    driver.FindElement(By.Id("Name")).Click();
    // 10 | type | id=Name | Selenium Create1
    driver.FindElement(By.Id("Name")).SendKeys("Selenium Create1");
    // 11 | click | id=Controller | 
    driver.FindElement(By.Id("Controller")).Click();
    // 12 | type | id=Controller | test1
    driver.FindElement(By.Id("Controller")).SendKeys("test1");
    // 13 | click | css=.row:nth-child(5) | 
    driver.FindElement(By.CssSelector(".row:nth-child(5)")).Click();
    // 14 | click | css=.row:nth-child(5) | 
    driver.FindElement(By.CssSelector(".row:nth-child(5)")).Click();
    // 15 | click | id=Action | 
    driver.FindElement(By.Id("Action")).Click();
    // 16 | type | id=Action | test1
    driver.FindElement(By.Id("Action")).SendKeys("test1");
    // 17 | click | id=Href | 
    driver.FindElement(By.Id("Href")).Click();
    // 18 | type | id=Href | test1
    driver.FindElement(By.Id("Href")).SendKeys("test1");
    // 19 | click | id=ParentId | 
    driver.FindElement(By.Id("ParentId")).Click();
    // 20 | click | id=ParentId | 
    driver.FindElement(By.Id("ParentId")).Click();
    // 21 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 22 | mouseOver | css=.btn-info | 
    {
      var element = driver.FindElement(By.CssSelector(".btn-info"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 23 | mouseOut | css=.btn-info | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 24 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 25 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 26 | type | css=.sorting_asc > .column_search | selen
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("selen");
    // 27 | click | css=.align-middle > .btn-info | 
    driver.FindElement(By.CssSelector(".align-middle > .btn-info")).Click();
    // 28 | click | id=Name | 
    driver.FindElement(By.Id("Name")).Click();
    // 29 | type | id=Name | Selenium Create2
    driver.FindElement(By.Id("Name")).SendKeys("Selenium Create2");
    // 30 | click | id=Controller | 
    driver.FindElement(By.Id("Controller")).Click();
    // 31 | type | id=Controller | test2
    driver.FindElement(By.Id("Controller")).SendKeys("test2");
    // 32 | click | id=Action | 
    driver.FindElement(By.Id("Action")).Click();
    // 33 | type | id=Action | test2
    driver.FindElement(By.Id("Action")).SendKeys("test2");
    // 34 | click | id=Href | 
    driver.FindElement(By.Id("Href")).Click();
    // 35 | type | id=Href | test2
    driver.FindElement(By.Id("Href")).SendKeys("test2");
    // 36 | click | css=.btn-info | 
    driver.FindElement(By.CssSelector(".btn-info")).Click();
    // 37 | type | css=.sorting_asc > .column_search | selen
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("selen");
  }
}
