// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RolListesiTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void rolListesi() {
    // Test name: Rol Listesi
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Rol İşlemleri | 
    driver.FindElement(By.LinkText("Rol İşlemleri")).Click();
    // 5 | click | linkText=Rol Listesi | 
    driver.FindElement(By.LinkText("Rol Listesi")).Click();
    // 6 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 7 | type | css=.sorting_asc > .column_search | selen
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("selen");
    // 8 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 9 | click | id=Name | 
    driver.FindElement(By.Id("Name")).Click();
    // 10 | type | id=Name | Selenium Create1
    driver.FindElement(By.Id("Name")).SendKeys("Selenium Create1");
    // 11 | click | id=Description | 
    driver.FindElement(By.Id("Description")).Click();
    // 12 | mouseOver | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3 > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 13 | type | id=Description | test1
    driver.FindElement(By.Id("Description")).SendKeys("test1");
    // 14 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 15 | mouseOut | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 16 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 17 | click | css=.breadcrumb-item:nth-child(2) | 
    driver.FindElement(By.CssSelector(".breadcrumb-item:nth-child(2)")).Click();
    // 18 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 19 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 20 | type | css=.sorting_asc > .column_search | selen
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("selen");
    // 21 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 22 | click | id=Name | 
    driver.FindElement(By.Id("Name")).Click();
    // 23 | type | id=Name | Selenium Create
    driver.FindElement(By.Id("Name")).SendKeys("Selenium Create");
    // 24 | click | id=Description | 
    driver.FindElement(By.Id("Description")).Click();
    // 25 | mouseOver | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3 > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 26 | type | id=Description | test
    driver.FindElement(By.Id("Description")).SendKeys("test");
    // 27 | click | css=.mt-3 > .btn | 
    driver.FindElement(By.CssSelector(".mt-3 > .btn")).Click();
    // 28 | mouseOut | css=.mt-3 > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 29 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 30 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 31 | click | css=.float-right:nth-child(1) | 
    driver.FindElement(By.CssSelector(".float-right:nth-child(1)")).Click();
    // 32 | click | css=.filter-option | 
    driver.FindElement(By.CssSelector(".filter-option")).Click();
    // 33 | click | css=li:nth-child(10) .text | 
    driver.FindElement(By.CssSelector("li:nth-child(10) .text")).Click();
    // 34 | click | css=.modal-footer > .waves-effect | 
    driver.FindElement(By.CssSelector(".modal-footer > .waves-effect")).Click();
    // 35 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 36 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 37 | mouseOver | css=.float-right:nth-child(1) | 
    {
      var element = driver.FindElement(By.CssSelector(".float-right:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 38 | click | css=.float-right:nth-child(1) | 
    driver.FindElement(By.CssSelector(".float-right:nth-child(1)")).Click();
    // 39 | mouseOut | css=.float-right:nth-child(1) | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 40 | click | css=.bs-placeholder | 
    driver.FindElement(By.CssSelector(".bs-placeholder")).Click();
    // 41 | click | css=li:nth-child(10) .text | 
    driver.FindElement(By.CssSelector("li:nth-child(10) .text")).Click();
    // 42 | click | css=.modal-footer > .waves-effect | 
    driver.FindElement(By.CssSelector(".modal-footer > .waves-effect")).Click();
    // 43 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 44 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 45 | click | css=.fa-trash-o | 
    driver.FindElement(By.CssSelector(".fa-trash-o")).Click();
    // 46 | mouseOver | css=.fa-trash-o | 
    {
      var element = driver.FindElement(By.CssSelector(".fa-trash-o"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 47 | mouseOut | css=.fa-trash-o | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 48 | click | css=.swal-button--confirm | 
    driver.FindElement(By.CssSelector(".swal-button--confirm")).Click();
    // 49 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 50 | click | css=.nav-item:nth-child(1) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(1) .hidden-xs-down")).Click();
    // 51 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 52 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 53 | type | css=.sorting_asc > .column_search | sel
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("sel");
    // 54 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 55 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
  }
}
