// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SzlemeListelemeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void szlemeListeleme() {
    // Test name: Sözleşme Listeleme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Sözleşme İşlemleri | 
    driver.FindElement(By.LinkText("Sözleşme İşlemleri")).Click();
    // 5 | click | linkText=Sözleşme Listesi | 
    driver.FindElement(By.LinkText("Sözleşme Listesi")).Click();
    // 6 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 7 | click | css=th:nth-child(4) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(4) > .column_search")).Click();
    // 8 | type | css=th:nth-child(4) > .column_search | 12.1
    driver.FindElement(By.CssSelector("th:nth-child(4) > .column_search")).SendKeys("12.1");
    // 9 | click | css=.container-fluid:nth-child(1) | 
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(1)")).Click();
    // 10 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 11 | click | css=.note-editable | 
    driver.FindElement(By.CssSelector(".note-editable")).Click();
    // 12 | mouseOver | css=.note-font > .note-btn:nth-child(3) | 
    {
      var element = driver.FindElement(By.CssSelector(".note-font > .note-btn:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 13 | mouseOut | css=.note-font > .note-btn:nth-child(3) | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 14 | mouseOver | css=.note-btn-underline | 
    {
      var element = driver.FindElement(By.CssSelector(".note-btn-underline"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 15 | mouseOut | css=.note-btn-underline | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 16 | editContent | css=.note-editable | test selenium
    {
      var element = driver.FindElement(By.CssSelector(".note-editable"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'test selenium'}", element);
    }
    // 17 | click | css=.row > .btn | 
    driver.FindElement(By.CssSelector(".row > .btn")).Click();
    // 18 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 19 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 20 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 21 | click | css=th:nth-child(4) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(4) > .column_search")).Click();
    // 22 | type | css=th:nth-child(4) > .column_search | 12.1
    driver.FindElement(By.CssSelector("th:nth-child(4) > .column_search")).SendKeys("12.1");
    // 23 | click | css=.container-fluid:nth-child(1) | 
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(1)")).Click();
    // 24 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 25 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 26 | mouseOver | css=.note-icon-orderedlist | 
    {
      var element = driver.FindElement(By.CssSelector(".note-icon-orderedlist"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 27 | mouseOut | css=.note-icon-orderedlist | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 28 | click | css=.note-editable | 
    driver.FindElement(By.CssSelector(".note-editable")).Click();
    // 29 | editContent | css=.note-editable | <p>&nbsp;test selenium2</p>
    {
      var element = driver.FindElement(By.CssSelector(".note-editable"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>&nbsp;test selenium2</p>'}", element);
    }
    // 30 | click | css=.row > .btn | 
    driver.FindElement(By.CssSelector(".row > .btn")).Click();
    // 31 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 32 | click | linkText=Liste | 
    driver.FindElement(By.LinkText("Liste")).Click();
    // 33 | click | css=th:nth-child(4) > .column_search | 
    driver.FindElement(By.CssSelector("th:nth-child(4) > .column_search")).Click();
    // 34 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 35 | type | css=th:nth-child(4) > .column_search | 12.1
    driver.FindElement(By.CssSelector("th:nth-child(4) > .column_search")).SendKeys("12.1");
    // 36 | click | css=.card:nth-child(3) > .card-body | 
    driver.FindElement(By.CssSelector(".card:nth-child(3) > .card-body")).Click();
    // 37 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 38 | runScript | window.scrollTo(0,1.600000023841858) | 
    js.ExecuteScript("window.scrollTo(0,1.600000023841858)");
    // 39 | click | css=.container-fluid | 
    driver.FindElement(By.CssSelector(".container-fluid")).Click();
    // 40 | editContent | css=.note-editable | <p>selam</p>
    {
      var element = driver.FindElement(By.CssSelector(".note-editable"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>selam</p>'}", element);
    }
    // 41 | click | css=.row > .btn | 
    driver.FindElement(By.CssSelector(".row > .btn")).Click();
    // 42 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
  }
}
