// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TbbibirimlerTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tbbibirimler() {
    // Test name: Tıbbi birimler
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Tıbbi Birimler | 
    driver.FindElement(By.LinkText("Tıbbi Birimler")).Click();
    // 5 | type | css=.sorting_asc > .column_search | 1608
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("1608");
    // 6 | click | id=dtMedicalUnits_wrapper | 
    driver.FindElement(By.Id("dtMedicalUnits_wrapper")).Click();
    // 7 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 8 | click | id=UnitName | 
    driver.FindElement(By.Id("UnitName")).Click();
    // 9 | type | id=UnitName | Kardiyoloji1
    driver.FindElement(By.Id("UnitName")).SendKeys("Kardiyoloji1");
    // 10 | click | id=UnitUrl | 
    driver.FindElement(By.Id("UnitUrl")).Click();
    // 11 | type | id=UnitUrl | https://www.memorial.com.tr/mobile-api/tibbi-birimlerimiz/kardiyoloji1
    driver.FindElement(By.Id("UnitUrl")).SendKeys("https://www.memorial.com.tr/mobile-api/tibbi-birimlerimiz/kardiyoloji1");
    // 12 | click | id=Description | 
    driver.FindElement(By.Id("Description")).Click();
    // 13 | mouseOver | css=.waves-light | 
    {
      var element = driver.FindElement(By.CssSelector(".waves-light"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 14 | type | id=Description | test açıklaması1
    driver.FindElement(By.Id("Description")).SendKeys("test açıklaması1");
    // 15 | click | css=.waves-light | 
    driver.FindElement(By.CssSelector(".waves-light")).Click();
    // 16 | mouseOut | css=.waves-light | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 17 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 18 | click | linkText=Tıbbi Birimler | 
    driver.FindElement(By.LinkText("Tıbbi Birimler")).Click();
    // 19 | type | css=.sorting_asc > .column_search | 1608
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("1608");
    // 20 | click | css=.container-fluid:nth-child(30) | 
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(30)")).Click();
    // 21 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 22 | click | id=UnitName | 
    driver.FindElement(By.Id("UnitName")).Click();
    // 23 | type | id=UnitName | Kardiyoloji
    driver.FindElement(By.Id("UnitName")).SendKeys("Kardiyoloji");
    // 24 | click | id=UnitUrl | 
    driver.FindElement(By.Id("UnitUrl")).Click();
    // 25 | type | id=UnitUrl | https://www.memorial.com.tr/mobile-api/tibbi-birimlerimiz/kardiyoloji
    driver.FindElement(By.Id("UnitUrl")).SendKeys("https://www.memorial.com.tr/mobile-api/tibbi-birimlerimiz/kardiyoloji");
    // 26 | click | id=Description | 
    driver.FindElement(By.Id("Description")).Click();
    // 27 | type | id=Description | test açıklaması
    driver.FindElement(By.Id("Description")).SendKeys("test açıklaması");
    // 28 | click | css=.waves-light | 
    driver.FindElement(By.CssSelector(".waves-light")).Click();
    // 29 | click | linkText=Hastane Bilgileri | 
    driver.FindElement(By.LinkText("Hastane Bilgileri")).Click();
    // 30 | click | css=.odd:nth-child(1) > td:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) > td:nth-child(3) .lever")).Click();
    // 31 | click | css=.even:nth-child(2) > td:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(2) > td:nth-child(3) .lever")).Click();
    // 32 | click | css=.nav-item:nth-child(3) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) .hidden-xs-down")).Click();
    // 33 | click | css=#dtDiasease .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtDiasease .odd:nth-child(1) .lever")).Click();
    // 34 | click | css=#dtDiasease .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtDiasease .even:nth-child(2) .lever")).Click();
    // 35 | click | css=.p-b-0 | 
    driver.FindElement(By.CssSelector(".p-b-0")).Click();
    // 36 | click | linkText=Tedaviler | 
    driver.FindElement(By.LinkText("Tedaviler")).Click();
    // 37 | click | css=#dtTreatment .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtTreatment .odd:nth-child(1) .lever")).Click();
    // 38 | click | css=#dtTreatment .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtTreatment .even:nth-child(2) .lever")).Click();
    // 39 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 40 | click | linkText=Tıbbi Birimler | 
    driver.FindElement(By.LinkText("Tıbbi Birimler")).Click();
    // 41 | click | css=.sorting_asc > .column_search | 
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).Click();
    // 42 | type | css=.sorting_asc > .column_search | 1608
    driver.FindElement(By.CssSelector(".sorting_asc > .column_search")).SendKeys("1608");
    // 43 | click | css=.fa-eye | 
    driver.FindElement(By.CssSelector(".fa-eye")).Click();
    // 44 | click | css=.nav-item:nth-child(2) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) .hidden-xs-down")).Click();
    // 45 | click | css=.odd:nth-child(1) > td:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(1) > td:nth-child(3) .lever")).Click();
    // 46 | click | css=.even:nth-child(2) > td:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".even:nth-child(2) > td:nth-child(3) .lever")).Click();
    // 47 | click | css=.nav-item:nth-child(3) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) .hidden-xs-down")).Click();
    // 48 | click | css=#dtDiasease .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtDiasease .odd:nth-child(1) .lever")).Click();
    // 49 | click | css=#dtDiasease .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtDiasease .even:nth-child(2) .lever")).Click();
    // 50 | click | css=.nav-item:nth-child(4) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) .hidden-xs-down")).Click();
    // 51 | click | css=#dtTreatment .odd:nth-child(1) .lever | 
    driver.FindElement(By.CssSelector("#dtTreatment .odd:nth-child(1) .lever")).Click();
    // 52 | click | css=#dtTreatment .even:nth-child(2) .lever | 
    driver.FindElement(By.CssSelector("#dtTreatment .even:nth-child(2) .lever")).Click();
    // 53 | click | css=#dtTreatment .odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector("#dtTreatment .odd:nth-child(1) .fa")).Click();
    // 54 | click | css=.switch:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector(".switch:nth-child(4) .lever")).Click();
    // 55 | mouseOver | css=.mt-3:nth-child(4) > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3:nth-child(4) > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 56 | click | css=.mt-3:nth-child(4) > .btn | 
    driver.FindElement(By.CssSelector(".mt-3:nth-child(4) > .btn")).Click();
    // 57 | mouseOut | css=.mt-3:nth-child(4) > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 58 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 59 | click | css=.close > span | 
    driver.FindElement(By.CssSelector(".close > span")).Click();
    // 60 | click | css=.nav-item:nth-child(3) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) .hidden-xs-down")).Click();
    // 61 | click | css=#dtDiasease .odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector("#dtDiasease .odd:nth-child(1) .fa")).Click();
    // 62 | mouseOver | css=#dtDiasease .odd:nth-child(1) .fa | 
    {
      var element = driver.FindElement(By.CssSelector("#dtDiasease .odd:nth-child(1) .fa"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 63 | mouseOut | css=#dtDiasease .odd:nth-child(1) .fa | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 64 | click | css=.switch:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector(".switch:nth-child(4) .lever")).Click();
    // 65 | mouseOver | css=.mt-3:nth-child(4) > .btn | 
    {
      var element = driver.FindElement(By.CssSelector(".mt-3:nth-child(4) > .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 66 | click | css=.mt-3:nth-child(4) > .btn | 
    driver.FindElement(By.CssSelector(".mt-3:nth-child(4) > .btn")).Click();
    // 67 | mouseOut | css=.mt-3:nth-child(4) > .btn | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 68 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 69 | click | css=.close > span | 
    driver.FindElement(By.CssSelector(".close > span")).Click();
    // 70 | click | css=#dtDiasease .odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector("#dtDiasease .odd:nth-child(1) .fa")).Click();
    // 71 | click | css=.close > span | 
    driver.FindElement(By.CssSelector(".close > span")).Click();
    // 72 | click | css=.nav-item:nth-child(4) .hidden-xs-down | 
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) .hidden-xs-down")).Click();
    // 73 | click | css=#dtTreatment .odd:nth-child(1) .fa | 
    driver.FindElement(By.CssSelector("#dtTreatment .odd:nth-child(1) .fa")).Click();
    // 74 | click | css=.close > span | 
    driver.FindElement(By.CssSelector(".close > span")).Click();
  }
}
