// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class YetkilendirmeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void yetkilendirme() {
    // Test name: Yetkilendirme
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://cms.memorial.4alabs.com/");
    // 2 | setWindowSize | 1752x1000 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1752, 1000);
    // 3 | click | linkText=Tanımlamalar | 
    driver.FindElement(By.LinkText("Tanımlamalar")).Click();
    // 4 | click | linkText=Yetki Yönetimi | 
    driver.FindElement(By.LinkText("Yetki Yönetimi")).Click();
    // 5 | click | linkText=Yetkilendirme | 
    driver.FindElement(By.LinkText("Yetkilendirme")).Click();
    // 6 | click | id=RoleId | 
    driver.FindElement(By.Id("RoleId")).Click();
    // 7 | select | id=RoleId | label=sil
    {
      var dropdown = driver.FindElement(By.Id("RoleId"));
      dropdown.FindElement(By.XPath("//option[. = 'sil']")).Click();
    }
    // 8 | click | id=btnSorgula | 
    driver.FindElement(By.Id("btnSorgula")).Click();
    // 9 | click | css=.odd:nth-child(2) > td:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(2) > td:nth-child(3) .lever")).Click();
    // 10 | click | css=.odd:nth-child(2) > td:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(2) > td:nth-child(4) .lever")).Click();
    // 11 | click | css=.odd:nth-child(2) > td:nth-child(5) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(2) > td:nth-child(5) .lever")).Click();
    // 12 | click | css=.odd:nth-child(2) > td:nth-child(6) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(2) > td:nth-child(6) .lever")).Click();
    // 13 | click | id=btnSave | 
    driver.FindElement(By.Id("btnSave")).Click();
    // 14 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 15 | click | id=btnSorgula | 
    driver.FindElement(By.Id("btnSorgula")).Click();
    // 16 | click | css=.odd:nth-child(2) > td:nth-child(3) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(2) > td:nth-child(3) .lever")).Click();
    // 17 | click | id=btnSave | 
    driver.FindElement(By.Id("btnSave")).Click();
    // 18 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 19 | click | id=btnSorgula | 
    driver.FindElement(By.Id("btnSorgula")).Click();
    // 20 | click | css=.odd:nth-child(2) > td:nth-child(4) .lever | 
    driver.FindElement(By.CssSelector(".odd:nth-child(2) > td:nth-child(4) .lever")).Click();
    // 21 | click | id=btnSave | 
    driver.FindElement(By.Id("btnSave")).Click();
    // 22 | mouseOver | id=btnSave | 
    {
      var element = driver.FindElement(By.Id("btnSave"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 23 | click | css=.swal-button | 
    driver.FindElement(By.CssSelector(".swal-button")).Click();
    // 24 | click | id=btnSorgula | 
    driver.FindElement(By.Id("btnSorgula")).Click();
  }
}
